[tool.poetry]
name = "how_transformer_llms_work"
version = "0.1.0"
description = ""
authors = ["Somesh Diwan"]

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
torch = "*"
sentencepiece = "*"
streamlit = "*"
numpy = "*"
matplotlib = "*"
fastapi = "*"
uvicorn = "*"

[tool.poetry.packages]
include = [{ include = "tokenizer" }]