[tool.poetry]
name = "how-transformer-llms-work"
version = "0.1.0"
description = "Transformer + Tokenizer + Streamlit demo"
authors = ["Somesh Diwan"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.14"
torch = "*"
sentencepiece = "*"
streamlit = "*"
matplotlib = "*"
numpy = "*"
fastapi = "*"
uvicorn = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"